<div class="bg-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading">Controle de Token</div>
    <div class="list-group list-group-flush">
        <a href="<?= $_ENV['BASE_URL'] ?>/home" class="list-group-item list-group-item-action bg-light">Início</a>
        <a href="<?= $_ENV['BASE_URL'] ?>/token/gerar" class="list-group-item list-group-item-action bg-light">Gerar Token</a>
        <a href="<?= $_ENV['BASE_URL'] ?>/token/consulta" class="list-group-item list-group-item-action bg-light">Consultar Tokens</a>
    </div>
</div>

