<h1 class="mt-4">Gerar Novo Token</h1>

<form action="<?= $_ENV['BASE_URL'] ?>/token/gerar" method="POST">
    <div class="form-group">
        <label for="paciente">Nome do Paciente</label>
        <input type="text" class="form-control" id="paciente" name="paciente" placeholder="Opcional">
    </div>
    <div class="form-group">
        <label for="codigo_paciente">Código do Paciente</label>
        <input type="text" class="form-control" id="codigo_paciente" name="codigo_paciente" placeholder="Opcional">
    </div>
    <button type="submit" class="btn btn-primary">Gerar Token</button>
</form>

