<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?? 'Controle de Token' ?></title>
    <!-- Inclua aqui seus arquivos CSS globais -->
    <!-- <link rel="stylesheet" href="<?= $_ENV['BASE_URL'] ?>/assets/css/bootstrap.min.css"> -->
    <!-- <link rel="stylesheet" href="<?= $_ENV['BASE_URL'] ?>/assets/css/estilov2.css"> -->
</head>
<body>
    <div class="d-flex" id="wrapper">
        <?php if (App\Core\Auth::isLogged()): ?>
            <?php require_once VIEWS_PATH . '/partials/sidebar.phtml'; ?>
        <?php endif; ?>

        <div id="page-content-wrapper">
            <?php if (App\Core\Auth::isLogged()): ?>
                <?php require_once VIEWS_PATH . '/partials/navbar.phtml'; ?>
            <?php endif; ?>

            <div class="container-fluid">
                <?= $pageContent ?? '' ?>
            </div>
        </div>
    </div>

    <!-- Inclua aqui seus arquivos JS globais -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="<?= $_ENV['BASE_URL'] ?>/assets/js/bootstrap.min.js"></script>
</body>
</html>

